### ISSUE TITLE
add mDNS local resolution so we can access the UI via http://name.local/ rather than just an IP

### ISSUE THREAD

**Issue by maggie0002** [maggie0002/balena-device-ui#42]

**Comment by maggie0002** [comment]
I thought devices were already accessible via the-hostname.local. Is the idea it will have a static name too?

**Comment by nucleardreamer** [comment]
Yes, the idea is to have a static name vs. remembering your `<uuid>.local` (by default) or needing to hit the IP address. #47 resolves this, letting you co-advertise the default `hostname.local` along side your specific name
