### ISSUE TITLE
Add testing 

### ISSUE THREAD

**Issue by nucleardreamer** [maggie0002/balena-device-ui#48]

**Comment by nucleardreamer** [comment]
I think we could do simple jsdoc on the API routes and generate a swagger file out of that? It seems like a bit of an investment but could be worthwhile in the long run if we are adding a lot of routes

**Comment by nucleardreamer** [comment]
Yep! auto generated API docs taken directly from express routes would be the best way to go about this I think. I will test out latest tools to see how convenient could be (remembering to swagger hell some years ago now)

**Comment by maggie0002** [comment]
There are plans to change the backend which will change the way the testing will work. It is on the project board for when that step is done so going to close this and track it on the project board instead.
