### ISSUE TITLE
Automate block publishing to balenaHub

### ISSUE THREAD

**Issue by chrisys** [maggie0002/balena-device-ui#79]
I finally got a chance to try the UI and went to use the block from balenaHub via the bh.cr URL, but noticed it's out of sync with the repo and needs updating.

Can we add the balena build action/workflow to automate the publishing of the block to hub and keep it in sync? Here's an example of another block which is publishing multiple architectures to hub as part of the workflow: https://github.com/balenablocks/browser/blob/master/.github/workflows/balena.yml

**Comment by maggie0002** [comment]
Yes, great idea, thanks for adding the issue. 

Is there a way to fix to a specific version when adding a Balena Cloud image to a Dockerfile (`FROM bh.cr/maggie0002/balena-device-ui:0.0.1`)? I had a tinker with some code over the weeks, which turned in to more than a tinker (as these things can often go). It will be significant, and likely more similar significant changes to come. Would be good if people could lock to a release to avoid breaking changes. Still going to push it of course, but if there isn't any versioning right now, will keep that in mind when pushing changes.

Might be nice to put together a GitHub repository template too for new projects. Both to kick off new projects, with the workflows added, but also for reference. 

If still looking to play around, maybe better to have a nose around at the pending pull request: https://github.com/maggie0002/balena-device-ui/pull/80

**Comment by chrisys** [comment]
> Is there a way to fix to a specific version when adding a Balena Cloud image to a Dockerfile

Yeah, but it would be `bh.cr/maggie0002/balena-device-ui/0.0.1`, more info [here](https://www.balena.io/blog/improving-device-image-management-workflow-balenaHub-Container-Registry/).

Thanks for the pointer about that PR!

**Comment by maggie0002** [comment]
I added the action, but at the moment it isn't working with the push on tag workflow on this repo. Added an issue for it here: https://github.com/balena-io/deploy-to-balena-action/issues/153

In the meantime I have done a manual push.
